name: auto version bump for sso plugin
on:
  push:
    branches:
      - '!*'
      - 'main'
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          persist-credentials: false

      - name:  'chordata-bot'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          minor-wording:  'feat'
          major-wording:  'breaking'
          patch-wording:  'fix,chore'
